#!/bin/bash
cmd_keys=( a c d f n o p r s t v w x y z / - =)
cmd_shift_keys=( n o p t w z )

# wip 
remove_ctrl_keys=()
remove_ctrl_shift_keys=()
# remove_ctrl_keys=( a c d f n o p r s t v w x y z / )
# remove_ctrl_shift_keys=( t w o z )

echo "; this file is automatically generated -- do no edit directly" > "$(dirname $0)/macCmdGenerated.ahk"

for key in "${remove_ctrl_keys[@]}"
do
  echo "
^$key::
return" >> "$(dirname $0)/macCmdGenerated.ahk"

done

for key in "${remove_ctrl_shift_keys[@]}"
do
  echo "
+^$key::
return" >> "$(dirname $0)/macCmdGenerated.ahk"

done

for key in "${cmd_keys[@]}"
do
  echo "
!$key::
Send, ^$key
return" >> "$(dirname $0)/macCmdGenerated.ahk"

done

for key in "${cmd_shift_keys[@]}"
do
  echo "
+!$key::
Send, +^$key
return" >> "$(dirname $0)/macCmdGenerated.ahk"

done
