; this file is automatically generated -- do no edit directly

!a::
Send, ^a
return

!c::
Send, ^c
return

!d::
Send, ^d
return

!f::
Send, ^f
return

!n::
Send, ^n
return

!o::
Send, ^o
return

!p::
Send, ^p
return

!r::
Send, ^r
return

!s::
Send, ^s
return

!t::
Send, ^t
return

!v::
Send, ^v
return

!w::
Send, ^w
return

!x::
Send, ^x
return

!y::
Send, ^y
return

!z::
Send, ^z
return

!/::
Send, ^/
return

!-::
Send, ^-
return

!=::
Send, ^=
return

+!n::
Send, +^n
return

+!o::
Send, +^o
return

+!p::
Send, +^p
return

+!t::
Send, +^t
return

+!w::
Send, +^w
return

+!z::
Send, +^z
return
